version: "3"
services:
  mariadb: #database config
    image: mariadb
    container_name: snipe-db
    restart: always
    volumes:
      - snipe-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD= #The root password
      - MYSQL_USER=snipe # a user to be created
      - MYSQL_PASSWORD= # that user's password
      - MYSQL_DATABASE=snipe # The database created for that user
  snipeit: #snipe-it config
    image: linuxserver/snipe-it:latest
    container_name: snipe-it
    restart: always
    depends_on:
      - mariadb
    volumes:
      - snipe-data:/config
    environment:
      - APP_URL= #< your application URL IE 192.168.10.1:8080>
      - MYSQL_PORT_3306_TCP_ADDR=127.0.0.1
      - MYSQL_PORT_3306_TCP_PORT=3306
      - MYSQL_DATABASE=snipe
      - MYSQL_USER=snipe
      - MYSQL_PASSWORD=
      - PGID=1000
      - PUID=1000
    ports:
      - "80:80"
      - "443:443"
volumes: #make sure the volumes are created on docker-compose up
 snipe-db:
    external: false
 snipe-data:
    external: false
 network:
     default:
     driver: bridge
