version: "3"
services:
  mariadb:
    image: mariadb
    container_name: snipe_db
    restart: always
    volumes:
      - /var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_USER=snipe
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=snipe
  snipeit:
    image: linuxserver/snipe-it:latest
    container_name: snipe-it
    restart: always
    depends_on:
      - mariadb
    volumes:
      - /config
    environment:
      - APP_URL=< your application URL IE 192.168.10.1:8080>
      - MYSQL_PORT_3306_TCP_ADDR=mysql
      - MYSQL_PORT_3306_TCP_PORT=3306
      - MYSQL_DATABASE=snipe
      - MYSQL_USER=snipe
      - MYSQL_PASSWORD=
      - PGID=1000
      - PUID=1000
    ports:
      - "80:80"
      - "443:443"
