version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: 'America/KentuckyLouisville'
    volumes:
       - './etc-pihole:/etc/pihole/:Z'
       - './etc-dnsmasq.d:/etc/dnsmasq.d/:Z'
    dns:
      - 127.0.0.1
      - 1.1.1.1
    restart: unless-stopped
